name: Generate Snake

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st of every month at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: mkasem06  # Replace with your GitHub username
          outputs: |
            dist/github-snake.gif
            dist/github-snake-dark.gif?palette=github-dark
            dist/github-snake.svg
      
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
